title: Damien Boisvert
url: "https://school.alphagame.dev"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "This website (and it's content) is copyright &copy; 2024 Damien Boisvert.  Some Rights Reserved."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 - name: "School"
   link: "/school/"
 - name: "I am A-G Ready"
   link: "/school/graduation/"
 - name: "AlphaGame.dev"
   link: "https://alphagame.dev/?utm_source=school.alphagame.dev&utm_medium=navbar"
